language: go

go:
  - 1.4
  - 1.5

env:
  - GO15VENDOREXPERIMENT=1

install:
  - go get github.com/Masterminds/glide
  - glide install

script: go test ./...

notifications:
  irc:
    channels:
      - "irc.freenode.org#tenyks"
      - "irc.freenode.org#infoforcefeed"
