language: go

go:
  - tip

env:
  - GO15VENDOREXPERIMENT=1

services:
  - redis-server

install:
  - echo noop

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libzmq4-dev

script: make test

notifications:
  irc:
    channels:
      - "irc.freenode.org#tenyks"
