language: go

go:
  - 1.2
  - 1.3
  - 1.4

install:
  - go get ./...
  - go get code.google.com/p/gomock/gomock

script: go test ./...

notifications:
  irc:
    channels:
      - "irc.freenode.org#tenyks"
