language: python
python:
    - 2.7

before_install:
    - sudo apt-get build-dep python-gevent

install:
    - python setup.py -q install

script:
    nosetests

notifications:
  irc:
    channels:
      - "irc.freenode.org#tenyks"
